# Generated by Django 5.1.5 on 2025-01-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('MX', 'Mexicano'), ('US', 'Americano'), ('JP', 'Japonês'), ('KR', 'Coreano'), ('CN', 'Chinês'), ('IN', 'Indiano'), ('UK', 'Britânico'), ('CA', 'Canadense'), ('AU', 'Australiano'), ('BR', 'Brasileiro'), ('RU', 'Russo'), ('FR', 'Francês'), ('DE', 'Alemão'), ('IT', 'Italiano'), ('ES', 'Espanhol'), ('AR', 'Argentino'), ('CO', 'Colombiano'), ('PE', 'Peruano'), ('VE', 'Venezuelano'), ('CL', 'Chileno'), ('EC', 'Equatoriano'), ('BO', 'Boliviano'), ('UY', 'Uruguaio'), ('PY', 'Paraguaio'), ('CR', 'Costarriquenho'), ('PA', 'Panamenho'), ('CU', 'Cubano'), ('DO', 'Dominicano'), ('GT', 'Guatemalteco'), ('SV', 'Salvadorenho'), ('HN', 'Hondurenho'), ('NI', 'Nicaraguense')], max_length=100, null=True)),
            ],
        ),
    ]
